version: '3.3'

networks:
  frontend:
  backend:

services:
  web:
    build: .
    volumes:
      - ./web:/var/www/html
    environment:
      VIRTUAL_HOST: chatter.docker
    links:
      - "database:database"
    ports:
      - "80"
  database:
    image: mysql:8
